// smartlab-frontend/src/Dashboard.styles.js

const styles = {
  dashboardLayout: {
    display: 'flex',
    minHeight: '100vh',
    backgroundColor: 'var(--bg-color)',
    fontFamily: "'Roboto', sans-serif",
    color: 'var(--text-color)',
    boxSizing: 'border-box',
    position: 'relative',
    transition: 'background-color 0.3s ease, color 0.3s ease',
  },
  sidebar: {
    backgroundColor: 'var(--bg-color-alt)',
    padding: '1rem 0',
    boxShadow: '4px 0 15px var(--shadow-color)',
    position: 'fixed',
    height: '100%',
    top: 0,
    left: 0,
    zIndex: 1000,
    transition: 'width 0.5s ease-in-out, background-color 0.3s ease',
    overflowX: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    boxSizing: 'border-box',
  },
  sidebarToggleButton: {
    position: 'absolute',
    top: '1rem',
    backgroundColor: 'var(--primary-color)',
    color: 'var(--primary-text-color)',
    border: 'none',
    borderRadius: '50%',
    width: '35px',
    height: '35px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    fontSize: '1rem',
    boxShadow: '0 2px 10px var(--shadow-color)',
    transition: 'background-color 0.3s ease, left 0.5s ease-in-out, right 0.5s ease-in-out, transform 0.2s ease',
    zIndex: 1001,
  },
  sidebarContent: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
    padding: '0 1rem',
    flexGrow: 1,
    opacity: 1,
    transition: 'opacity 0.3s ease-in-out 0.2s',
    boxSizing: 'border-box',
    overflowY: 'auto',
    marginTop: '3rem',
  },
  sidebarTitle: {
    fontSize: '2rem',
    marginBottom: '1.5rem',
    color: 'var(--primary-color)',
    textShadow: '0 0 10px var(--shadow-color-light)',
  },
  sidebarUserInfo: {
    fontSize: '1.1rem',
    fontWeight: 'bold',
    marginBottom: '0.8rem',
    color: 'var(--text-color)',
    textAlign: 'center',
  },
  sidebarDetail: {
    fontSize: '0.85rem',
    color: 'var(--text-color-muted)',
    marginBottom: '0.4rem',
    textAlign: 'center',
    wordBreak: 'break-word',
    width: '100%',
  },
  mainContent: {
    flexGrow: 1,
    padding: '2rem',
    paddingTop: '2rem',
    boxSizing: 'border-box',
    width: '100%',
    minWidth: 0,
    paddingLeft: '100px',
    transition: 'padding-left 0.5s ease-in-out',
  },
  title: {
    fontSize: '2.5rem',
    marginBottom: '1.5rem',
    color: 'var(--text-color)',
    textShadow: '0 0 12px var(--shadow-color-light)',
    textAlign: 'center',
  },
  roleHighlight: {
    fontWeight: '700',
    color: 'var(--primary-color)',
    textShadow: '0 0 5px var(--shadow-color-light)',
  },
  cardContainer: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
    gap: '1.5rem',
    width: '100%',
    maxWidth: '1200px',
    marginBottom: '3rem',
    margin: '0 auto 3rem auto',
  },
  card: {
    backgroundColor: 'var(--bg-color-alt)',
    padding: '1.5rem',
    borderRadius: '12px',
    boxShadow: '0 6px 20px var(--shadow-color)',
    textAlign: 'center',
    border: '1px solid var(--border-color)',
    transition: 'background-color 0.3s ease, border-color 0.3s ease',
  },
  statNumber: {
    fontSize: '2.5em',
    fontWeight: '700',
    color: 'var(--success-color)',
    margin: '0.5rem 0 0',
    textShadow: '0 0 8px rgba(39, 174, 96, 0.4)',
  },
  section: {
    backgroundColor: 'var(--bg-color-alt)',
    padding: '1.8rem',
    borderRadius: '12px',
    boxShadow: '0 4px 15px var(--shadow-color)',
    width: '100%',
    maxWidth: '1200px',
    marginBottom: '2.5rem',
    border: '1px solid var(--border-color)',
    scrollMarginTop: '20px',
    margin: '0 auto 2.5rem auto',
    transition: 'background-color 0.3s ease, border-color 0.3s ease',
  },
  managementSection: {
    marginTop: '1.5rem',
    paddingTop: '1rem',
    borderTop: '1px dashed var(--text-color-muted)',
  },
  sectionTitle: {
    fontSize: '1.6rem',
    marginBottom: '1rem',
    color: 'var(--text-color)',
    borderBottom: '2px solid var(--border-color)',
    paddingBottom: '0.6rem',
    textShadow: '0 0 8px var(--shadow-color-light)',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  subSectionTitle: {
    fontSize: '1.2rem',
    marginBottom: '0.8rem',
    color: 'var(--text-color)',
    textShadow: '0 0 5px var(--shadow-color-light)',
    textAlign: 'center',
  },
  list: {
    listStyleType: 'none',
    padding: '0',
    marginTop: '1rem',
  },
  listItem: {
    backgroundColor: 'var(--list-item-bg)',
    padding: '1rem',
    marginBottom: '0.7rem',
    borderRadius: '8px',
    borderLeft: '5px solid var(--list-item-border)',
    lineHeight: '1.5',
    wordBreak: 'break-word',
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
    boxShadow: '0 2px 8px var(--shadow-color)',
    transition: 'background-color 0.3s ease, border-color 0.3s ease',
  },
  adminNotes: {
    fontSize: '0.85rem',
    color: 'var(--text-color-muted)',
    marginTop: '0.4rem',
    fontStyle: 'italic',
  },
  bookingStatus: {
    APPROVED: { color: 'var(--success-color)', fontWeight: 'bold' },
    PENDING: { color: 'var(--warning-color)', fontWeight: 'bold' },
    REJECTED: { color: 'var(--error-color)', fontWeight: 'bold' },
    CANCELLED: { color: 'var(--text-color-muted)', fontWeight: 'bold' },
    COMPLETED: { color: 'var(--primary-color)', fontWeight: 'bold' },
  },
  toggleFormButton: {
    padding: '0.7rem 1.3rem',
    backgroundColor: 'var(--primary-color)',
    color: 'var(--primary-text-color)',
    border: 'none',
    borderRadius: '8px',
    fontSize: '0.95em',
    cursor: 'pointer',
    marginBottom: '1.2rem',
    transition: 'background-color 0.3s ease, transform 0.2s ease',
  },
  toggleSectionButton: {
    backgroundColor: 'transparent',
    border: 'none',
    color: 'var(--text-color-muted)',
    padding: '0.5rem',
    borderRadius: '5px',
    cursor: 'pointer',
    transition: 'background-color 0.3s ease, color 0.3s ease, transform 0.2s ease',
    lineHeight: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  toggleIcon: {
    width: '20px',
    height: '20px',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.8rem',
    marginTop: '1.2rem',
  },
  formContainer: {
    backgroundColor: 'var(--form-container-bg)',
    padding: '1.2rem',
    borderRadius: '10px',
    boxShadow: 'inset 0 0 10px rgba(47, 128, 237, 0.05)',
    marginTop: '1.2rem',
    marginBottom: '1.5rem',
    border: '1px dashed var(--form-container-border)',
    transition: 'background-color 0.3s ease, border-color 0.3s ease',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
  },
  label: {
    marginBottom: '0.4rem',
    fontWeight: '500',
    color: 'var(--text-color-muted)',
    fontSize: '0.9rem',
  },
  input: {
    padding: '0.7rem 0.9rem',
    border: '1px solid var(--border-color)',
    borderRadius: '8px',
    backgroundColor: 'var(--bg-color-alt)',
    color: 'var(--text-color)',
    fontSize: '0.95rem',
    boxSizing: 'border-box',
    transition: 'border-color 0.3s ease, box-shadow 0.3s ease, background-color 0.3s ease, color 0.3s ease',
  },
  submitButton: {
    padding: '0.8rem 1.6rem',
    backgroundColor: 'var(--success-color)',
    color: 'var(--primary-text-color)',
    border: 'none',
    borderRadius: '8px',
    fontSize: '1rem',
    fontWeight: 'bold',
    cursor: 'pointer',
    marginTop: '1.2rem',
    transition: 'background-color 0.3s ease, transform 0.2s ease, box-shadow 0.3s ease',
  },
  actionButtons: {
    display: 'flex',
    gap: '0.6rem',
    marginTop: '0.8rem',
    justifyContent: 'flex-end',
    flexWrap: 'wrap',
  },
  approveButton: { backgroundColor: 'var(--success-color)', color: 'white', border: 'none', borderRadius: '6px', padding: '0.5rem 0.9rem', cursor: 'pointer', fontSize: '0.85em', transition: 'background-color 0.3s ease, transform 0.2s ease' },
  rejectButton: { backgroundColor: 'var(--error-color)', color: 'white', border: 'none', borderRadius: '6px', padding: '0.5rem 0.9rem', cursor: 'pointer', fontSize: '0.85em', transition: 'background-color 0.3s ease, transform 0.2s ease' },
  cancelButton: { backgroundColor: 'var(--cancel-color)', color: 'var(--warning-text-color)', border: 'none', borderRadius: '6px', padding: '0.5rem 0.9rem', cursor: 'pointer', fontSize: '0.85em', transition: 'background-color 0.3s ease, transform 0.2s ease' },
  deleteButton: { backgroundColor: 'var(--error-color)', color: 'white', border: 'none', borderRadius: '6px', padding: '0.5rem 0.9rem', cursor: 'pointer', fontSize: '0.85em', transition: 'background-color 0.3s ease, transform 0.2s ease' },
  editButton: { backgroundColor: 'var(--primary-color)', color: 'white', border: 'none', borderRadius: '6px', padding: '0.5rem 0.9rem', cursor: 'pointer', fontSize: '0.85em', transition: 'background-color 0.3s ease, transform 0.2s ease' },
  viewPeripheralsButton: { backgroundColor: '#56CCF2', color: '#1F2933', border: 'none', borderRadius: '6px', padding: '0.5rem 0.9rem', cursor: 'pointer', fontSize: '0.85em', transition: 'background-color 0.3s ease, transform 0.2s ease' },
  simpleActionButton: { padding: '0.7rem 1.3rem', backgroundColor: 'var(--primary-color)', color: 'var(--primary-text-color)', border: 'none', borderRadius: '8px', fontSize: '0.95em', fontWeight: 'bold', cursor: 'pointer', marginTop: '0.8rem', transition: 'background-color 0.3s ease, transform 0.2s ease, box-shadow 0.3s ease' },
  createButton: { padding: '0.7rem 1.3rem', backgroundColor: 'var(--success-color)', color: 'white', border: 'none', borderRadius: '8px', fontSize: '0.95em', fontWeight: 'bold', cursor: 'pointer', marginTop: '1.2rem', marginBottom: '0.8rem', transition: 'background-color 0.3s ease, transform 0.2s ease' },
  backButton: { padding: '0.5rem 0.9rem', backgroundColor: '#9B51E0', color: 'white', border: 'none', borderRadius: '6px', fontSize: '0.85em', cursor: 'pointer', marginTop: '0.8rem', marginBottom: '0.8rem', transition: 'background-color 0.3s ease, transform 0.2s ease' },
  buttonGroup: { display: 'flex', gap: '0.8rem', flexWrap: 'wrap', justifyContent: 'center', marginTop: '1.2rem', },
  successMessage: { color: 'var(--success-color)', fontWeight: 'bold', textAlign: 'center', marginTop: '1.2rem', textShadow: '0 0 8px rgba(39, 174, 96, 0.5)', fontSize: '0.9em' },
  errorMessage: { color: 'var(--error-color)', fontWeight: 'bold', textAlign: 'center', marginTop: '1.2rem', textShadow: '0 0 8px rgba(235, 87, 87, 0.5)', fontSize: '0.9em'},
  logoutButtonWithIcon: {
    backgroundColor: 'transparent',
    border: '1px solid var(--error-color)',
    borderRadius: '8px',
    padding: '0.5rem',
    cursor: 'pointer',
    marginTop: 'auto',
    marginBottom: '1rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'background-color 0.3s ease, transform 0.2s ease, border-color 0.3s ease',
    alignSelf: 'center',
    width: 'auto',
  },
  logoutIcon: {
    width: '24px',
    height: '24px',
    display: 'block',
  },
  loading: { color: 'var(--primary-color)', fontSize: '1.8rem', textAlign: 'center', minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'var(--bg-color)', },
  noDataText: { color: 'var(--text-color-muted)', fontStyle: 'italic', marginTop: '1rem', fontSize: '0.9em' },
  peripheralsGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: '0.8rem', marginTop: '0.8rem', padding: '0.8rem', backgroundColor: 'var(--form-container-bg)', borderRadius: '8px', border: '1px dashed var(--form-container-border)', },
  peripheralItem: { backgroundColor: 'var(--bg-color-alt)', padding: '0.8rem', borderRadius: '8px', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', fontSize: '0.9rem', textAlign: 'center', color: 'var(--text-color)', border: '1px solid var(--border-color)', boxShadow: '0 2px 8px var(--shadow-color)', },
  peripheralInput: { width: '70px', padding: '0.4rem', marginTop: '0.5rem', borderRadius: '5px', border: '1px solid var(--primary-color)', backgroundColor: 'var(--bg-color-alt)', color: 'var(--text-color)', textAlign: 'center', fontSize: '0.95em', },
  warningMessage: { color: 'var(--warning-color)', fontSize: '0.9em', marginTop: '0.8rem', textAlign: 'center', textShadow: '0 0 5px rgba(242, 153, 74, 0.3)', },
  chartsContainer: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(350px, 1fr))', gap: '2rem', marginTop: '1.2rem', },
  chartWrapper: { padding: '1.2rem', border: '1px solid var(--border-color)', borderRadius: '10px', backgroundColor: 'var(--bg-color-alt)', boxShadow: '0 4px 12px var(--shadow-color)', transition: 'background-color 0.3s ease, border-color 0.3s ease', },
  navbar: { display: 'flex', flexDirection: 'column', gap: '0.6rem', width: '100%', marginTop: '1.5rem', marginBottom: '1.5rem', padding: '0', alignItems: 'stretch', },
  navLink: {
    color: 'var(--text-color-muted)',
    textDecoration: 'none',
    fontWeight: '500',
    fontSize: '1em',
    padding: '0.6rem 0.8rem',
    borderRadius: '8px',
    transition: 'background-color 0.3s ease, color 0.3s ease, box-shadow 0.3s ease, transform 0.2s ease',
    textAlign: 'center',
    backgroundColor: 'transparent',
    border: '1px solid transparent',
  },
  navLinkActive: {
    backgroundColor: 'var(--primary-color)',
    color: 'var(--primary-text-color)',
    fontWeight: 'bold',
    boxShadow: '0 0 10px var(--shadow-color-light)',
    transform: 'scale(1.05)',
  },

  // ***** NOVOS ESTILOS PARA O BOTÃO DE TEMA *****
  themeToggleButton: {
    padding: '0.7rem 1.3rem',
    backgroundColor: 'transparent',
    color: 'var(--primary-color)',
    border: '1px solid var(--primary-color)',
    borderRadius: '8px',
    fontSize: '0.9em',
    cursor: 'pointer',
    transition: 'background-color 0.3s ease, color 0.3s ease, transform 0.2s ease',
    marginBottom: '1rem',
    fontWeight: 'bold',
  },
  themeToggleButtonClosed: {
      width: '40px',
      height: '40px',
      padding: '0',
      fontSize: '1.2rem',
      marginBottom: '0.5rem',
      marginTop: 'auto', 
  },
};

export default styles;